### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by YumeGod** [Kiana1337/GamesenseLuaCloudloader#1]
1. Try to avoid using the gamesense http library, instead of using gamesense http library, use steam http service by ffi calling
2. Try to use asymmetric encryption to encrypt the http body
3. Hide http url (path), for example change "/login" to "/RandomString"
4. Add timestamp to each message, and validate it on server side to prevent replay attack
5. Use ECDH algorithm, and assign each user different key pairs (since in ECDH, you can have different client key pairs but the same server key pair)

**Comment by ryusei423** [comment]
Great advice, I know very little about anti-leakage
Thanks for the info and have a nice day

**Comment by YumeGod** [comment]
> Great advice, I know very little about anti-leakage
> Thanks for the info and have a nice day

Thanks for your contribution to gamesense community :)
